[package]
name = "urlq"
version = "0.1.0"
authors = ["Ulf Åhammar <ulfahammar@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
structopt = "0.2"
either = "1.5"
percent-encoding = "1.0.1"
url = "1.7.2"
atty = "0.2"
